language: node_js
node_js:
- node
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run build
- yarn run test
deploy:
  provider: npm
  email: khoa.tan.nguyen.96@gmail.com
  api_key:
    secure: NuaSuJdgP7tU+kVpppVjKAm5Ry6Q1KBCsDKrdWDtK/gHNciZDAHP1ll0tRJ5vmAEsF8OjA1O6ersdo4WdnvU3zTiNacvf9vRqvdaa9LKsE8kVaKZlh6HtEc/eXFAvIIwDjiGzzEFbuEip9pahtXCY5OglDv99V01UK5lVRv0eFRu61Sg7lm6rR9TOwdtONWAVFenb117y5HqcjNPjCj2VVRR3WPRhGwWgClvaJlcS2oRJjZCXs/6mfhz7zIjzYMurmDyI1aNy1v9O1lT4TIILmikpxR+SOfz2hkmdTHUBYKsCKnYXrFYOwLUIEoBfDpDVI6RimYRZkAFy45J27WHR4mnEwihgC91i8BF47A7LKDMKa6GRGtiNQJMCIW3T/gxFpE7tQ+KRYjv6pHmOhSXpjSQLM/wi52AmlhRt2RLZz08AHNDz0g7AMHU8MzDs39Bm3LuEJo2f2tZU/fhX18LsUlUqBNENiLO99wdJhMpXl93/nilBBYbWzrOMomYVemgEJLwRoxGLeJBGe+O0PMPrF3dqTMlCK25HbbTf8tJl79vANvK8VKj0B+QfA155mn0dwnDND9Ow95EIVko3P0jXOFMZLxcT+WXMn5l6Ss7iEx3MBPNNTrlrnHCoxzZQcH0mMWUbMN2nKwX0vCs94EHV7443S8VTuKtcbFqJ/2Dnk8=
  on:
    tags: true
    repo: khoanguyen96/vue-paypal-checkout
